### ISSUE TITLE
Change function name of `_get_template_details` in Stack class

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#11]
The function name does not accurately describe the purpose. Function actually returns either the AWS S3 url or template string.

**Comment by theseanything** [comment]
@jamesroutley thinking to rename to boto_parameter or boto_argument or call_argument something like that and moving the function to template class

**Comment by jamesroutley** [comment]
I think the reason we're having difficulty with this function name is because the function itself isn't very good. 

The function does the following:
- Decide whether the cfn template should be uploaded to S3
- If it should, upload it to S3 and return a dictionary containing a key-value pair which happens to correspond to a keyword argument to a Boto3 function call (!)
- If not, return the a dictionary containing a key-pair ...

The function does different things (either returns the template location or the template itself), and returns a value which is highly coupled to the context of the function's invoker.

The reason that this function exists is that this logic happens multiple times in `Stack()` (when creating, launching, validating and creating a change set). We are caught between two 'bad' practices: including a badly defined, tightly coupled function, or having repeated code.

There are a couple of things we could do:
1. Leave the code as is, but give it a better name
2. Remove the function and re-add the repeated code
3. Rearchitect it in some way to solve the underlying problem

I think we should go for 1. or 2. for now, and maybe have a look at 3. when we're looking at the 2.0 stuff. @seanrankine thoughts on this so far?

**Comment by theseanything** [comment]
I don't think the function is necessarily bad - don't see any issue with it functionality. Its main goal to create the keyword argument for boto calls depending on how to handle the template body. Its just badly named. 

Overall I was looking at moving validate_template to the template class as well, which also needs this function.  So was going to move this function to template class as well.

**Comment by b-t-g** [comment]
Closed by #209.
