### ISSUE TITLE
Clarify MS Windows support

### ISSUE THREAD

**Issue by tlkcr** [cloudreach/sceptre#151]
It would be worth clarifying if sceptre is supported on Windows (and others?) OS.

 For exemple, running a stack in Windows using !stack_output with path in yaml files won't run as expected and throw an error:

`list object has no element 1`

**Comment by jamesroutley** [comment]
Huh interesting. So we theoretically support Windows because it's all just Python so *should* work cross platform. None of the development team have Windows machines though, so I guess bugs are more likely. Do you have any idea what might be causing the issue? I know that anecdotally some people have used Sceptre on Windows fine.

**Comment by jamesroutley** [comment]
Could you send us your stack config file?

**Comment by tlkcr** [comment]
Ok so it looks like any features using $path at some point are buggy. Especially because paths are always considered in sceptre splitted by '/'(slash) rather than '\'(back-slash) which on Windows cause wrong comparisons.
This behavior as been observed in environment.py when looking for loop dependencies but *might* exists somewhere else.

**Comment by GouldSJ** [comment]
We have observed a similar issue. When trying to implement a cascading configuration of environments and running this locally via Git bash on a windows platform it fails to generate valid names for the stacks. this is due to the environments using os calls to get the path, which is used to generate the stack name,  and the use of a hard coded "/" path separator in helpers.py (line 157).

There are 2 possible solutions to this:
1) use of -
def convertPath(path):
	# Convert windows, mac path to unix version.
 	separator = os.path.normpath("/")
 	if separator != "/":
 		path = re.sub(re.escape(separator), "/", path)

wherever an os call is used to return a file or directory path

2) use os.path.sep everywhere instead of hardcoding "/"

I suspect option 1 will have less impact and will be sufficient.

It would be great if you could prioritise this as it is effecting the implementation of one of cloudreach's public sector clients.

Cheers

**Comment by theseanything** [comment]
This issue contains a few different problems, which I have split off into separate issues - #156 #157 #158. Please use the relevant issue for further discussion.
