### ISSUE TITLE
sceptre launch-env ignores top-level stacks

### ISSUE THREAD

**Issue by mikkoc** [cloudreach/sceptre#224]
Potentially related to https://github.com/cloudreach/sceptre/issues/159
I have the following directory structure:
```
config/component/sub-component/stacks.yaml
config/component/top-level-stack.yaml
```

I launch sceptre like this:
```
sceptre --var-file=environments/dev.yaml launch-env component
```

But sceptre completely ignores `top-level-stack.yaml` in the parent folder, and only creates/updates the sub-component stacks.

**Comment by theseanything** [comment]
Hi @mikkoc, this is intended behavior - only stacks within 'leaf' environments (i.e. environments that don't contain other environments) can be launched. 

In your case `sub-component` is a leaf environment hence `stacks.yaml` can be launched. However because `component` environment has the `sub-component` environment, it is not a leaf environment and `top-level-stack.yaml` cannot be launched. If you were to put `top-level-stack.yaml` into another leaf environment under `component` it would work.
