### ISSUE TITLE
Support calling resolvers from Jinja templates

### ISSUE THREAD

**Issue by ianburrell** [cloudreach/sceptre#243]
Currently, resolvers can only be used in parameters. If they were available in the Jinja template, then  they could be used in other places, like template_path (#71).

It looks like Jinja2 can add functions to environment globals that can then be called from templates:

`
{{ environment_variable('PATH') }}
`

**Comment by theseanything** [comment]
Hey @ianburrell, this wouldn't be possible due implementation details - jinja is sort of a pre-processing step - and the whole config needs to be read in before resolvers can run. But we could look at extending use of resolvers in all parts of the config, rather than just `parameters` and `sceptre_user_data`
