### ISSUE TITLE
Better error message for trying to action on stack in non-leaf environment.

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#249]
Currently, an non-specific error message is presented `AttributeError: 'Environment' object has no attribute 'stacks'` when you try to action a stack within a non-leaf environment. A better error message should be presented like `Environment contains sub-environments. Stack must be in leaf environment.`

**Comment by ngfgrant** [comment]
@theseanything looking through the stacktrace on #248 the issue also arose in a non-leaf environment. 

However, the error was ValueError rather than AttributeError. The `recurrse_into_sub_environments` function line 52 in ```helpers.py``` might be the cause of the described AttributeError. The ValueError reported in #248 probably arose from line 49 where max_workers=0. 

We could try handle the case where num_environments = 0 a better, might be two issues with one stone?

**Comment by b-t-g** [comment]
@theseanything, could we simplify the message even further? Something like `Stacks must be in an environment with no sub-environments`? While I do agree that the graph-theoretic term "leaf" is well-known, should we expect end-users to know it off the top of their heads?

**Comment by ngfgrant** [comment]
This is going to be a non-issue when cascading config is removed in version 2.
