### ISSUE TITLE
The diff command that was part of 2.0 disappeared in the merge. Mistake?

### ISSUE THREAD

**Issue by oazmon** [cloudreach/sceptre#305]
The diff command that was part of 2.0 disappeared in the merge. Mistake?

**Comment by ngfgrant** [comment]
Hi @oazmon 

Looks like it was removed in 1.3.1 (2017.10.23)

https://github.com/cloudreach/sceptre/blob/34234a8e56529822f0377786875ff8c698e6d3a9/HISTORY.rst

The commit that reverted this functionality was: e0b2849796872ad6b197b7cf7ec2cc9b8cd618e1

@theseanything is away on holiday at the moment but seems this was a conscious decision rather than a mistake.
