### ISSUE TITLE
Cannot get launch-env working

### ISSUE THREAD

**Issue by robertwnorris** [cloudreach/sceptre#394]
Apologies if this is not the correct place to ask this question.

I’ve been playing around with Sceptre for creating an ECS cluster with a single service. I have everything working when using launch-stack for each template but when I try and use launch-env it fails.
 
The reason it’s failing is because it is creating the stacks in the wrong order. I have three stacks: vpc, cluster, and component (which creates ECS task and service). I’ve tried using the dependencies section of the config but it doesn’t make any difference. I have vpc configured with no dependencies, the cluster has the vpc set as dependency, and the component has the vpc and the cluster set as dependencies.

When I run launch-env with nothing previously created it tries to create the component first but fails, then the cluster but fails and finally the vpc which succeeds. If I run launch-env again the component will fail but the cluster will now succeed as the vpc exists.

I’m either doing something silly or just missing how launch-env should be used.
Any help or guidance would be much appreciated.

Cheers,
Rob

**Comment by jeshan** [comment]
Instead of putting all your templates for a certain environment flat in the same path, use sub-directories. Sceptre will treat these as "sub-environments" (if that makes any sense). Example for your test env, you can have:

test/
├── cluster
│   └── ecs.yaml
├── config.yaml
├── frontend
│   └── my-frontend-stack.yaml
└── infrastructure
    └── vpc.yaml

Then to invoke in your desired order:
```
sceptre launch-env test/infrastructure
sceptre launch-env test/cluster
sceptre launch-env test/frontend
```

**Comment by robertwnorris** [comment]
Thanks for the information.

What I was looking for was a single command to build an environment. I can already do what you are suggesting just using multiple launch-stack command. I was assuming that launch-env would do something similar to a build system in that it would use dependencies to determine build order. 
  
It’s not a major problem, it just means I need a script with a few lines instead of just one. The only downside it that I had hoped that with more complex environments some stacks could be create in parallel speeding things up.

**Comment by jeshan** [comment]
ok maybe there's something on [the roadmap](https://github.com/cloudreach/sceptre/wiki/Roadmap) to address what you're saying.
If you use `launch-env` as I showed, the stacks in each of the logical groups are launched in parallel and will make your build faster instead of using individual `launch-stack`

**Comment by rdkr** [comment]
This sounds like it could be related to #159?

**Comment by ngfgrant** [comment]
@robertwnorris @rdkr - yeh looks like #159 would probably resolve this. The good news is that it is on the roadmap for `v1.3.5`, the bad news is that work has currently not started on it. 

I am going to close this issue, if there are any further questions though please feel free to open it up again.
