### ISSUE TITLE
How to use dependencies across subfolders within config?

### ISSUE THREAD

**Issue by craighurley** [cloudreach/sceptre#433]
Is it possible to use `dependencies` when config contains subfolders?

For example, using this folder structure...

```
├── config
│   └── dev
│       ├── a
│       │   └── app1.yaml
│       │   └── app2.yaml
│       ├── b
│       │   └── appB1.yaml
│       ├── config.yaml
├── templates
```

Essentially it's the approach described as "DevOps team who manage all the infrastructure for thier service" on this page: https://sceptre.cloudreach.com/latest/docs/architecture.html

`config/dev/b/appB1.yaml` looks like this:

```
template_path: templates/appB1.yaml
stack_tags:
  Application: {{ environment_config.project_code }}
  Environment: {{ environment_config.environment }}
  Owner: {{ environment_config.owner }}
dependencies:
    - dev/a/app1
```

1. I deploy using `sceptre launch-env dev/a` which completes successfully
1. I then try deploying b like this `sceptre launch-env dev/b`, but I get the following error:

    ```
    Traceback (most recent call last):
    File "/Users/craig.hurley/.pyenv/versions/aws/bin/sceptre", line 11, in <module>
        sys.exit(cli())
    File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/aws/lib/python3.6/site-packages/click/core.py", line 716, in __call__
        return self.main(*args, **kwargs)
    File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/aws/lib/python3.6/site-packages/click/core.py", line 696, in main
        rv = self.invoke(ctx)
    File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/aws/lib/python3.6/site-packages/click/core.py", line 1060, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/aws/lib/python3.6/site-packages/click/core.py", line 889, in invoke
        return ctx.invoke(self.callback, **ctx.params)
    File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/aws/lib/python3.6/site-packages/click/core.py", line 534, in invoke
        return callback(*args, **kwargs)
    File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/aws/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
        return f(get_current_context(), *args, **kwargs)
    File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/aws/lib/python3.6/site-packages/sceptre/cli.py", line 96, in decorated
        return func(*args, **kwargs)
    File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/aws/lib/python3.6/site-packages/sceptre/cli.py", line 315, in launch_env
        response = env.launch()
    File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/aws/lib/python3.6/site-packages/sceptre/environment.py", line 127, in launch
        self._check_for_circular_dependencies()
    File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/aws/lib/python3.6/site-packages/sceptre/environment.py", line 351, in _check_for_circular_dependencies
        [stack.name]
    File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/aws/lib/python3.6/site-packages/sceptre/helpers.py", line 193, in _detect_cycles
        dependency = available_nodes[dependency_name.split("/")[-1]]
    KeyError: 'app1'
    ```

**Comment by vazkarvishal** [comment]
I was going to ask a question which is very similar to this one. Have you tried using Resolvers?  Here is a reference on [How to use resolvers](https://sceptre.cloudreach.com/latest/docs/resolvers.html)

you coukd achieve this by either using stack_output or the stack_output_external resolver as shown below:

Example of a stack output which has been provisioned using sceptre
```bash
parameters | sceptre_user_data:
    <name>: !stack_output <stack_name>::<output_name>

## The above with an example

parameters:
    VpcIdParameter: !stack_output shared/vpc::VpcIdOutput

```
and then use the VpcIdParameter as a ref value on your CF template which should give you what you need and as you are using resolvers, the dependent stack will automatically wait for the parent stack to be created first.

Let me know if this is helpful.

## A question on the same lines with a slightly different context

I was more worried about a use-case as below. If someone from Cloudreach can answer this question then it would be of great help.

What if, in the interest of introducing DevOps as a culture within development teams, we want to give developers access to provision their own ECS services, but the network experts / DevOps engineers to own the VPC and underlying network provisioning? we want to do this using separate GIT repositories. In this case, will updating the parent stack fail if the dependant stacks are not a part of the same sceptre deployment?

e.g.

Repository-A - github repository for DevOps Engineers
Repository-B (Developer Repository)

```yaml
-  Repository A
  - vpc.yml
  - subnets.yml
  - internet gateway
  - ECS Cluster
  - Loadbalancer
```
Developer responsibility:

```yaml
-  Repository B
  - ECS Service
  - Loadbalancer listener rule
  - ECS Service
  - ECR repository
```

**Situation - Based on the above 2 snippets**
using the above example, assuming that everything from Repository A has been deployed successfully and ready to use, the developers have consumed the resources from Repository-A to create a listener rule. This listener rule is created in Repository-B which is a completely separate repo to Repository-A.

**Question**
When the DevOps engineers now want to update the Subnets / Loadbalancers on Repository-A, will the update-stack operation fail because it has been consumed by others and thus not treated as a nested CF stack? or will Sceptre allow the underlying VPC and Loadbalancer changes to work successfully?


Thanks,
Vishal

**Comment by jaymecd** [comment]
Sceptre builds list of dependencies only direct path hierarchy, see [v1.3.4/sceptre/environment.py#L306](https://github.com/cloudreach/sceptre/blob/v1.3.4/sceptre/environment.py#L306) for more info.

There are two ways to solve such problems:
1. use `!output_stack_external` resolver, but as argument full stack name from CloudFormation have to specified.
2. write another resolver for project absolute patch lookup

For the second option I could suggest following:

```python
from sceptre.resolvers.stack_output import StackOutputBase

class StackOutputAbs(StackOutputBase):
    """
    Resolver for retrieving the value of an output of project stack by absolute path, while stack is not added to dependency list.

    :param argument: The stack name and output name to get.
    :type argument: str in the format ``"<project stack name>::<output key>"``
    """

    def __init__(self, *args, **kwargs):
        super(StackOutputAbs, self).__init__(*args, **kwargs)

    def resolve(self):
        """
        Retrieves the value of Cloudformation output of the project stack by absolute path.

        :returns: The value of the stack output.
        :rtype: str
        """
        self.logger.debug(
            "Resolving root stack output: {0}".format(self.argument)
        )
        dependency_stack_name, output_key = self.argument.split("::")

        stack_name = "-".join([
            self.environment_config["project_code"],
            dependency_stack_name.replace("/", "-")
        ])

        return self._get_output_value(stack_name, output_key)
```

Save this snippet to `resolvers/stack_output_abs.py` and adjust configs with `!stack_output_abs` where you you have not direct cross directory linking.

**Comment by ngfgrant** [comment]
This is related to #159

**Comment by ngfgrant** [comment]
As an update to this I have been working on resolving this issue is a robust way as part of #482. In `v2` you will be able to reference stacks as dependencies and have them resolve properly (as well as their dependencies) by just using `dependencies:` in your stack. @vazkarvishal your question looks good and I don't want to lose it can you open a new issue with it?

Thanks @craighurley and @jaymecd for highlighting this!
