### ISSUE TITLE
Unable to install sceptre using python 3.7

### ISSUE THREAD

**Issue by vazkarvishal** [cloudreach/sceptre#436]
Hello,

I have tried to install sceptre using python 3.7 (as that is the version which gets installed with brew) and am having trouble trying to install the tool. The error is as given below:

`$ Failed building wheel for PyYaml`

Following that error, I have done some looking around and realised that PyYaml have released a latest version **3.13** which resolves the wheel issues. However, on running **pip install sceptre** the setup goes and uninstalls the 3.13 version which was installed earlier in the setup and then falls over complaining about PyYaml.

![image](https://user-images.githubusercontent.com/13076513/42826588-b0695e1e-89dc-11e8-994a-2b70eebf1729.png)

I have had to fall back to use 2.x for now, but is this something you guys can hotfix on your installer so that it supports python 3.7 installations please?

Thanks,
Vishal

**Comment by jeshan** [comment]
issue #413 already open

**Comment by ngfgrant** [comment]
Hey Vishal, 

From a Python point of view, for now we support Python 3.6 and there are no immediate plans to "support" Python 3.7; that's not to say we won't support 3.7; but for now there are bigger fish to fry.

Looking at our `requirements.txt`, it looks like `PyYaml==3.12`. That is probably is something we can update without much controversy in `v1.3.5`. It is also the source of your issues. 

If you need to move quickly, I would recommend cloning the git tagged `v1.3.4` and then modifying the requirements so that `PyYaml==3.13`. You will then need to:

`pip install -e "path-to-your-sceptre-install/"`

If you aren't already I would recommend using a virtualenv. 

I will use this issue as a tracker to update the requirements file for the next v1 release, which I am aiming to get released by the end of the month.

**Comment by ngfgrant** [comment]
Correction: I will close this issue and use #431 to track the discussion, it was open first and this is a duplicate.

**Comment by vazkarvishal** [comment]
Hello,

Thanks for the update. I can wait till the end of the month and just work off the 2.x installation I have at the moment.
 Virtualenv: yes I am using this. Have it setup locally and a requirements,.txt created with sceptre on there too!

Thanks,
Vishal
