### ISSUE TITLE
Normalise OS paths v2

### ISSUE THREAD

**Issue by ryanpagel** [cloudreach/sceptre#531]
Running sceptre generate in v2.0 is giving the following error: `ValueRrror: max() arg is an empty sequence`.  Any ideas on this?  I'm just doing a barebones with one template.
![image](https://user-images.githubusercontent.com/805791/49326423-be444c00-f517-11e8-9a6b-c53c44dcf2cc.png)

**Comment by ryanpagel** [comment]
Here's the whole thing in a screenshot.  Am I missing something simple here?
![image](https://user-images.githubusercontent.com/805791/49329469-f57d2200-f544-11e8-9a6f-565cb610f21d.png)

**Comment by janrotter** [comment]
It's a windows specific issue.

Here:
https://github.com/cloudreach/sceptre/blob/master/sceptre/config/reader.py#L206
the `abs_path` equals to:
`c:\myproj\config\dev\test.yaml`
while `full_command_path` is:
`c:\myproj\config\dev/test.yaml`
(**mind the slash!**)

This results in the stack not being added to the command stacks and the exception above.

@ryanpagel could you please try to run `sceptre generate dev\test.yaml` as a workaround (the backslash instead of a forward slash)?

**Comment by ngfgrant** [comment]
Yeh I have a local branch for this. We tried to catch the Windows incompatible path manipulations from v1 but looks like a couple slipped though. Will get a patch out this week with a couple of other small things. We are looking to use Python's `os.sep` where we need to split out paths.

**Comment by ngfgrant** [comment]
Hi @ryanpagel I have removed the last of the path manipulations that would be causing any issues with windows. Once merged, you should be able to just use normal Windows path separators (`\`) in your commands. I will also update the docs to make sure other Windows users are aware.

**Comment by ryanpagel** [comment]
@janrotter That seems to work, although I'd prefer to use the same path separators as Unix, which used to work on Windows as sceptre 1.x.  @ngfgrant  I'll look for that minor version release soon, thanks!

**Comment by ngfgrant** [comment]
@mike-rsi I am working on a branch at the moment to resolve this so you can use as in v1.

**Comment by ngfgrant** [comment]
#531 and #616 will resolve the initial request here. Better DOS path support also on the way with #535

**Comment by mike-rsi** [comment]
I noticed this got bumped from the last two releases. Is there a complication with the solution? Anything I can do to help? I've really been waiting for this one.  Thanks.

**Comment by ngfgrant** [comment]
@mike-rsi would be really useful to get some help with this, I've not got a windows box so testing this properly has been a bit slow. As you noticed it has been a couple of months since I was last able to look at this. 

Looking at my commits so far I think I was trying to go for the following:

- when sceptre interacts with the file system and stores paths we should use `os.sep` which will give us the correct path to read configs and stacks.

- when sceptre interacts with itself or the outside world (AWS) the paths of the stacks need to be use `/` as their separator. 

Context should be the only place where we need to store path info.

The good news is whatever the next release is it will 100% have this in it along with a fix for the recursion error that's been happening.

**Comment by ngfgrant** [comment]
@ryanpagel and @mike-rsi I have updated the branch `normalise-os-paths` (https://github.com/cloudreach/sceptre/tree/normalise-os-paths). Would either of you be willing to checkout the branch and test. Everything seemed to work well in my windows vm.

Cheers,
Niall

**Comment by mike-rsi** [comment]
@ngfgrant Finally using Sceptre on a project again and had a chance to test this.  Sceptre itself seems to work great now, but the `!stack_output` resolver does not.  A work-around now is to define explicit `stack_name` properties in each stack config and use `!stack_output_external` instead. Not ideal, but a good step forward as the code base doesn't have to change between OSes.  This iteration of the bug seems to be documented in https://github.com/cloudreach/sceptre/issues/716 now, but I figure I'd add my update here as it's related.

**Comment by ngfgrant** [comment]
I think there is a fix in #719 which will be in 2.1.4... maybe worth checking out that branch and testing with that?

**Comment by mike-rsi** [comment]
@ngfgrant Branch 2.1.4 seems to work, thanks!
