### ISSUE TITLE
Spelling mistakes in documentation

### ISSUE THREAD

**Issue by vlatko-onica** [cloudreach/sceptre#642]
"This configuration will be used by the **create, update, and create commands**. "

"A custom **name name** to use instead of the Sceptre default."

**Comment by 1oglop1** [comment]
@vlatko-onica Thanks for reporting it!

@ngfgrant I will fix this in my branch for new version of docs

both errors seems to come from `stack_config`

I fixed 
`A custom name name to use instead of the Sceptre default.` -> 
`A custom name to use instead of the Sceptre default.` 


However I'm not entirely sure about
`This configuration will be used by the create, update, and create commands. ` ->
`This configuration will be used by the create, update, and delete commands. ` ?
