### ISSUE TITLE
Better Installation instructions

### ISSUE THREAD

**Issue by johnculkin** [cloudreach/sceptre#78]
Sceptre needs some better installation instructions. My recent experience installing Sceptre from Github wasn't as smooth as I would have liked. 

I'd like something that talks about the recommended tools to install beforehand - Ex: virtualenv/virtualenvwrapper - Troposphere (with awacs). I could create a shell script to run these - thoughts? 

I'll write something up and create a PR

**Comment by theseanything** [comment]
Thanks @johnculkin! I would list the steps, rather than creating a script - as the steps I ran through with you were recommended, but not mandatory to get sceptre running.

Those steps were - for MacOS:
`brew install python`
`pip install virtualenv`
`pip install virtualenvwrapper`
(add lines to bashrc)
`mkvirtualenv sceptre`
`pip install sceptre`
`pip install troposphere` - if your using troposphere templates. (Optional!)

**Comment by johnculkin** [comment]
ok I like it -  Here is my first quick and dirty attempt - I'll see if Mr Mossman would like to test it for me 

`brew install python

pip install virtualenv
pip install virtualenvwrapper

mkdir ~/virtualenvs

cat <<EOF >> ~/.bash_profile 
export WORKON_HOME=~/virtualenvs
source /usr/local/bin/virtualenvwrapper.sh
EOF

source ~/.bash_profile

mkvirtualenv venv1
workon venv1

pip install troposphere
pip install awacs
pip install sceptre`

**Comment by jamesroutley** [comment]
I think we'd do better to just link to a proper Python install guide than rewrite it here. Something like [this](http://docs.python-guide.org/en/latest/starting/installation/) and [this](http://docs.python-guide.org/en/latest/dev/virtualenvs/) would be more thorough and more likely to be kept up to date.

**Comment by theseanything** [comment]
+1 for link to proper install guide - but we may want to look at adding a note the readme, saying this the ideal way for running sceptre etc...
